paths:
  project: C:\Users\santi\OneDrive\Dokumente\Age-Estimation\Code\unsplash
  images: original_images
  bodies: bodies
  faces: faces
  tables: tables
  export: final_output

detect:
  yolo_body: yolov8n.pt
  img_size_body: 640 
  body_conf_thres: 0.25
  nms_iou_thres: 0.5
  deepface_backend: yolov8
  face_conf_thres: 0.5

runtime:
  batch_size: 16
  seed: 1337

schema:
  images: [image_id, image_path, width, height]
  bodies: [image_id, body_id, body_conf, file_name]
  faces: [image_id, body_id, face_id, face_conf, file_name, gender, race, age_deepface, age_mivolo, sharpness, brightness, contrast, usable]

quality:
  min_sharpness: 50.0
  min_contrast: 15.0
  min_brightness: 30.0
  max_brightness: 220.0
  min_face_size: 112

train:
  out_dataset: dataset_age_cls
  split: {train: 0.8, val: 0.1, test: 0.1}
  age_priority: [age_mivolo, age_deepface]
  target_per_class: 1200  
